-- MySQL Script generated by MySQL Workbench
-- Wed Jul 12 11:06:54 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema plataformaEDU0198
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema plataformaEDU0198
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `plataformaEDU0198` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `plataformaEDU0198` ;

-- -----------------------------------------------------
-- Table `plataformaEDU0198`.`alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plataformaEDU0198`.`alumnos` (
  `id_alumno` INT NOT NULL AUTO_INCREMENT,
  `grado` VARCHAR(7) NULL,
  `grupo` VARCHAR(3) NULL,
  `matricula` INT(11) NULL,
  `nombre` VARCHAR(50) NULL,
  `apellido_paterno` VARCHAR(45) NULL,
  `apellido_materno` VARCHAR(45) NULL,
  `promedio_general` VARCHAR(15) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(15) NULL,
  `fecha_registro` DATETIME NULL,
  `ultimo_acceso` DATETIME NULL,
  PRIMARY KEY (`id_alumno`),
  UNIQUE INDEX `matricula_UNIQUE` (`matricula` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plataformaEDU0198`.`maestros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plataformaEDU0198`.`maestros` (
  `id_maestro` INT NOT NULL AUTO_INCREMENT,
  `matricula` INT(11) NULL,
  `grupo` VARCHAR(7) NULL,
  `nombre` VARCHAR(50) NULL,
  `apellido_paterno` VARCHAR(45) NULL,
  `apellido_materno` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(15) NULL,
  `fecha_registro` DATETIME NULL,
  `ultimo_acceso` DATETIME NULL,
  PRIMARY KEY (`id_maestro`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `matricula_UNIQUE` (`matricula` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plataformaEDU0198`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plataformaEDU0198`.`cursos` (
  `id_curso` INT NOT NULL AUTO_INCREMENT,
  `grado` VARCHAR(7) NULL,
  `clave_curso` VARCHAR(10) NULL,
  `materia` VARCHAR(50) NULL,
  `nombre_curso` VARCHAR(50) NULL,
  `objetivos_generales` VARCHAR(300) NULL,
  PRIMARY KEY (`id_curso`),
  UNIQUE INDEX `clave_curso_UNIQUE` (`clave_curso` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plataformaEDU0198`.`unidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plataformaEDU0198`.`unidades` (
  `id_unidad` INT NOT NULL AUTO_INCREMENT,
  `no_unidad` VARCHAR(10) NULL,
  `nombre_unidad` LONGTEXT NULL,
  `presentacion` LONGTEXT NULL,
  PRIMARY KEY (`id_unidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plataformaEDU0198`.`preguntas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plataformaEDU0198`.`preguntas` (
  `id_pregunta` INT NOT NULL AUTO_INCREMENT,
  `no_pregunta` INT(10) NULL,
  `pregunta` VARCHAR(99) NULL,
  `respuesta_a` VARCHAR(99) NULL,
  `respuesta_b` VARCHAR(99) NULL,
  `respuesta_c` VARCHAR(99) NULL,
  `respuesta_d` VARCHAR(99) NULL,
  `respuesta_correcta` VARCHAR(2) NULL,
  PRIMARY KEY (`id_pregunta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plataformaEDU0198`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plataformaEDU0198`.`administrador` (
  `id_administrador` INT NOT NULL AUTO_INCREMENT,
  `cargo` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido_paterno` VARCHAR(45) NULL,
  `apellido_materno` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `fecha_registro` DATETIME NULL,
  `ultimo_acceso` DATETIME NULL,
  PRIMARY KEY (`id_administrador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plataformaEDU0198`.`respuestas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plataformaEDU0198`.`respuestas` (
  `id_respuesta` INT NOT NULL AUTO_INCREMENT,
  `no_respuesta` INT(10) NULL,
  `respuesta` VARCHAR(2) NULL,
  PRIMARY KEY (`id_respuesta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plataformaEDU0198`.`calificaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plataformaEDU0198`.`calificaciones` (
  `id_calificacion` INT NOT NULL AUTO_INCREMENT,
  `calificacion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_calificacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plataformaEDU0198`.`temas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plataformaEDU0198`.`temas` (
  `id_tema` INT NOT NULL AUTO_INCREMENT,
  `no_tema` VARCHAR(10) NULL,
  `nombre_tema` VARCHAR(45) NULL,
  `descripcion_tema` VARCHAR(100) NULL,
  `contenido_tema` LONGTEXT NULL,
  `url_tema` VARCHAR(100) NULL,
  PRIMARY KEY (`id_tema`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
